set_bypass_mode:
  name: Set bypass mode
  description: Set the bypass mode for the BRINK HRU unit
  target:
    device:
  fields:
    mode:
      name: Bypass mode
      description: The bypass mode to set
      required: true
      selector:
        select:
          options:
            - "automatic"
            - "closed"
            - "open"

set_flow_speed:
  name: Set flow speed
  description: Set the target flow speed for the BRINK HRU unit
  target:
    device:
  fields:
    speed:
      name: Flow speed
      description: Target flow speed in m³/h
      required: true
      selector:
        number:
          min: 50
          max: 325
          step: 5
          unit_of_measurement: "m³/h"

set_power_mode:
  name: Set power mode
  description: Set the power switch position for the BRINK HRU unit
  target:
    device:
  fields:
    mode:
      name: Power mode
      description: The power mode to set
      required: true
      selector:
        select:
          options:
            - "absence"
            - "low"
            - "normal"
            - "high"

reset_device:
  name: Reset device
  description: Reset the BRINK HRU device (use with caution)
  target:
    device:

read_all_registers:
  name: Read all registers
  description: Read all Modbus registers for diagnostics (returns data as event)
  target:
    device:
